name: Moodle plugin CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      mariadb:
        image: mariadb:10.11
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_CHARACTER_SET_SERVER: utf8mb4
          MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: "8.1"
            moodle-branch: MOODLE_401_STABLE
          - php: "8.1"
            moodle-branch: MOODLE_405_STABLE
    steps:
      - name: Check out plugin
        uses: actions/checkout@v4
        with:
          path: plugin

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          ini-values: max_input_vars=5000

      - name: Install Moodle Plugin CI
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo "$(cd ci/bin && pwd)" >> "$GITHUB_PATH"
          echo "$(cd ci/vendor/bin && pwd)" >> "$GITHUB_PATH"

      - name: Install Moodle test locale
        run: |
          sudo locale-gen en_AU.UTF-8
          sudo update-locale

      - name: Install test site
        run: moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: mariadb
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHP lint
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phplint

      - name: Moodle coding standard
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpcs --max-warnings 0

      - name: Moodle PHPDoc
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpdoc --max-warnings 0

      - name: PHP mess detector
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpmd

      - name: Copy-paste detector
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpcpd

      - name: Plugin validation
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci validate

      - name: Upgrade savepoints
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci savepoints

      - name: PHPUnit
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpunit --fail-on-warning

      - name: Behat
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci behat --profile chrome --start-servers
